export const teamData = [
    { name: "Falak Yadav", role: "CTO & Co-Founder", department: "Tech", avatar: "FY", image: "/images/team_members/falak.jpeg", linkedin: "https://www.linkedin.com/in/falak-yadav/", color: "#8EB9FF", description: "Chief Technology Officer and Co-Founder. Visionary tech builder focused on creating scalable platforms that enable meaningful human connection and skill exchange." },
    { name: "Pragati Singh", role: "Growth Intern", department: "Growth", avatar: "PS", image: "/images/team_members/pragati.jpeg", color: "#FFB3D9", description: "Writer who turns ideas into meaningful stories that connect people and products. Currently pursuing B.Tech and exploring growth through content and creativity." },
    { name: "Khyati", role: "Growth Intern", department: "Growth", avatar: "KH", image: "/images/team_members/khyati.jpeg", color: "#FFD96A", description: "Academic scholar and school captain with experience in debates, science congresses, and national events. Passionate about leadership, community building, and creative expression." },
    { name: "Harima", role: "Growth Intern", department: "Growth", avatar: "HA", image: "/images/team_members/harima.jpeg", color: "#D6C4FF", description: "Interested in startups, research, and growth strategy. Enjoys fast-paced environments and contributing to impactful ideas." },
    { name: "Naira M", role: "Growth Head", department: "Growth", avatar: "NM", image: "", linkedin: "https://www.linkedin.com/in/naira-m/", color: "#8EB9FF", description: "Focused on building growth-driven ecosystems. Believes in turning skill trading into a lifestyle and scaling meaningful movements." },
    { name: "Karan Choudhary", role: "App Developer", department: "Tech", avatar: "KC", image: "/images/team_members/karan.jpeg", linkedin: "https://www.linkedin.com/in/karan-choudhary-8b62a6216/", color: "#8EB9FF", description: "Backend-focused developer interested in scalable systems, data pipelines, and building reliable software." },
    { name: "Ritvik Nayak", role: "Developer", department: "Tech", avatar: "RN", image: "/images/team_members/ritvik.jpeg", linkedin: "https://www.linkedin.com/in/ritvik-nayak/", color: "#FFB3D9", description: "Full-stack developer passionate about building elegant solutions and bringing creative ideas to life through code." },
    { name: "Aditya Raj Tiwari", role: "Tech Developer", department: "Tech", avatar: "AT", image: "/images/team_members/aditya_raj.jpg", linkedin: "https://www.linkedin.com/in/aditya-raj-tiwari-36a3b5293/", color: "#FFD96A", description: "Creative problem solver skilled in coding, storytelling, and media. Brings a blend of technical and communication skills." },
    { name: "Aksh Tiwari", role: "App Developer", department: "Tech", avatar: "AT", image: "", linkedin: "https://www.linkedin.com/in/akshtiwariweb/", color: "#D6C4FF", description: "Frontend-focused developer and UI designer specializing in web development, cloud, networking, and creative development." },
    { name: "Aditi S.", role: "Marketing Head", department: "Marketing", avatar: "AD", image: "/images/team_members/aditi.jpg", linkedin: "https://www.linkedin.com/in/aditie21/", color: "#FFB3D9", description: "Creative thinker with interests in poetry, piano, and chess. Focused on thoughtful practice and continuous improvement." },
    { name: "Eva Y", role: "Community & Outreach Manager", department: "Marketing", avatar: "EV", image: "/images/team_members/eva.jpeg", linkedin: "https://www.linkedin.com/in/eva-y-2177a92b3/", color: "#8EB9FF", description: "Passionate about STEM, research, and meaningful innovation. Enjoys deep work, creativity, and contributing to impactful solutions." },
    { name: "Hansika Mulani", role: "Creative Strategist", department: "Marketing", avatar: "HM", image: "/images/team_members/hansika.jpeg", linkedin: "https://www.linkedin.com/in/hansika-mulani-534844389/", color: "#FFD96A", description: "Energetic and creative individual who loves exploring ideas and bringing people together. Dance and expression play a big role in her life." },
    { name: "Nandini Y", role: "Content Writer", department: "Marketing", avatar: "NY", image: "/images/team_members/nandini.jpeg", linkedin: "https://www.linkedin.com/in/nayndini/", color: "#D6C4FF", description: "Content writer who enjoys crafting perspectives through words. Interested in psychology, neuroscience, and creative expression." },
    { name: "Shreeti M.", role: "Content Writer", department: "Marketing", avatar: "SM", image: "/images/team_members/shreeti.jpeg", linkedin: "https://www.linkedin.com/in/shreeti-mohapatra/", color: "#8EB9FF", description: "Uses writing to connect, inform, and inspire. Focused on meaningful conversations through words." },
    { name: "Ishani Sharma", role: "Chief of Staff & Partnerships", department: "Management", avatar: "IS", image: "/images/team_members/ishani.jpeg", linkedin: "https://www.linkedin.com/in/ishani-sharma-724271320/", color: "#FFB3D9", description: "Finance major passionate about accessibility, collaboration, and impact. Enjoys solving complex problems and building opportunities." },
    { name: "Syed Azmaan", role: "Partnerships & Hiring", department: "Management", avatar: "SA", image: "/images/team_members/syed.jpeg", linkedin: "https://www.linkedin.com/in/syed-azmaan-ali-madni-99642b230/", color: "#FFD96A", description: "Curious thinker driven by conversations and ideas that create impact." },
    { name: "Anwesha Ganji", role: "Founder & CEO", department: "Management", avatar: "AG", image: "/images/team_members/anwesha.png", linkedin: "https://www.linkedin.com/in/anwesha-g-861785344/", color: "#D6C4FF", description: "Builder focused on entrepreneurship, research, and design. Leads Swapifhy with a vision to make collaboration and learning more accessible." }
];

export const features = [
    { img: "/images/features/meetpeoplenearyou.png", title: "meet people near you", desc: "find people around you. learn together. meet in real life if you want.", glow: "from-swap-blue/20" },
    { img: "/images/features/learnandteachatthesametime.png", title: "learn and teach simultaneously", desc: "you help someone learn something that you know. they help you learn something new.", glow: "from-swap-pink/20" },
    { img: "/images/features/earncredits.png", title: "earn credits when you help others", desc: "everytime you teach, you earn credits. use those credits to learn more things", glow: "from-swap-gold/20" },
    { img: "/images/features/aroundtheworld.png", title: "learning happening globally", desc: "watch swaps light up on a live map. people learning everywhere in realtime.", glow: "from-swap-lavender/20" },
    { img: "/images/features/buildtogether.png", title: "build things together", desc: "join challenges, mini-projects, and hackathons. don't just learn - make stuff.", glow: "from-swap-blue/20" },
    { img: "/images/features/realconvo.png", title: "real humans, real conversations", desc: "free 1-on-1 live sessions, no videos, no bots. just people helping people", glow: "from-swap-pink/20" }
];
