export const teamData = [
    {
        name: "Anwesha Ganji",
        role: "Founder & CEO",
        department: "Management",
        avatar: "AG",
        level: 0,
        image: "/images/team_members/anwesha.png",
        linkedin: "https://www.linkedin.com/in/anwesha-g-861785344/",
        xSocial: "https://x.com/anwesha_ganji",
        color: "linear-gradient(135deg, #8EB9FF, #D6C4FF)",
        text: "#000",
        description: "Visionary leads Swapifhy with a mission to make collaboration and peer-to-peer learning accessible for everyone."
    },
    {
        name: "Falak Yadav",
        role: "CTO & Co-Founder",
        department: "Tech",
        avatar: "FY",
        level: 0,
        image: "/images/team_members/falak.jpg",
        linkedin: "https://www.linkedin.com/in/falak-yadav-a61199241/",
        xSocial: "",
        color: "linear-gradient(135deg, #8EB9FF, #D6C4FF)",
        text: "#000",
        description: "Chief Technology Officer focused on building high-bandwidth exchange protocols and scalable tech architecture."
    },
    {
        name: "Soha Wasti",
        role: "Chief Marketing Officer",
        department: "Marketing",
        avatar: "SW",
        level: 1,
        image: "/images/team_members/soha.png",
        linkedin: "https://www.linkedin.com/in/soha-wasti-a325442a9/",
        xSocial: "",
        color: "linear-gradient(135deg, #8EB9FF, #D6C4FF)",
        text: "#000",
        description: "Leading the marketing strategy and growth engine for Swapifhy — building brand awareness, driving user acquisition, and creating localized trust across the ecosystem."
    },
    {
        name: "Naira M",
        role: "Growth Head",
        department: "Growth",
        avatar: "NM",
        level: 1,
        image: "",
        linkedin: "https://www.linkedin.com/in/naira-m/",
        xSocial: "",
        color: "linear-gradient(135deg, #8EB9FF, #D6C4FF)",
        text: "#000",
        description: "Driving growth-led ecosystems and scaling meaningful human connection movements."
    },
    {
        name: "Aditya Raj Tiwari",
        role: "Core Tech Lead & Architect",
        department: "Tech",
        avatar: "AT",
        level: 1,
        image: "/images/team_members/aditya_raj.jpg",
        linkedin: "https://www.linkedin.com/in/aditya-raj-tiwari-36a3b5293/",
        xSocial: "",
        color: "linear-gradient(135deg, #8EB9FF, #D6C4FF)",
        text: "#000",
        description: "Leading technical growth and shaping the future of high-performance connections at Swapifhy."
    },
    {
        name: "Ishani Sharma",
        role: "Chief of Staff & Partnerships",
        department: "Management",
        avatar: "IS",
        level: 1.5,
        image: "/images/team_members/ishani.jpeg",
        linkedin: "https://www.linkedin.com/in/ishani-sharma-724271320/",
        xSocial: "",
        color: "linear-gradient(135deg, #8EB9FF, #D6C4FF)",
        text: "#000",
        description: "Specializing in partnerships, financial accessibility, and operational impact. Shaping the organizational backbone of the protocol."
    },
    {
        name: "Eva Y",
        role: "Community & Outreach Head",
        department: "Marketing",
        avatar: "EV",
        level: 2,
        image: "/images/team_members/eva.jpeg",
        linkedin: "https://www.linkedin.com/in/eva-y-2177a92b3/",
        xSocial: "",
        color: "linear-gradient(135deg, #8EB9FF, #D6C4FF)",
        text: "#000",
        description: "Community builder shaping innovation and high-impact STEM outreach. Orchestrating the network's human nodes."
    },
    {
        name: "Karan Choudhary",
        role: "Core App Architect",
        department: "Tech",
        avatar: "KC",
        level: 2.5,
        image: "/images/team_members/karan.jpeg",
        linkedin: "https://www.linkedin.com/in/karan-choudhary-8b62a6216/",
        xSocial: "https://x.com/aisenh_037",
        color: "linear-gradient(135deg, #8EB9FF, #D6C4FF)",
        text: "#000",
        description: "Shaping the technical foundation and building reliable, high-performance backend systems."
    },
    {
        name: "Ritvik Nayak",
        role: "Web Developer",
        department: "Tech",
        avatar: "RN",
        level: 2.5,
        image: "",
        linkedin: "https://www.linkedin.com/in/ritvik-nayak/",
        xSocial: "",
        color: "linear-gradient(135deg, #8EB9FF, #D6C4FF)",
        text: "#000",
        description: "Full-stack builder dedicated to crafting elegant code and seamless UX. Shaping the digital interaction layer."
    },
    {
        name: "Nandini Y",
        role: "Content Writer",
        department: "Marketing",
        avatar: "NY",
        level: 3.5,
        image: "/images/team_members/nandini.jpeg",
        linkedin: "https://www.linkedin.com/in/nayndini/",
        xSocial: "",
        color: "linear-gradient(135deg, #8EB9FF, #D6C4FF)",
        text: "#000",
        description: "Crafting narratives focused on psychology, neuroscience, and expression. Shaping the intellectual voice of the Swapifhy protocol."
    },
    {
        name: "Pragati Singh",
        role: "Growth Intern",
        department: "Growth",
        avatar: "PS",
        level: 5,
        image: "/images/team_members/pragati.jpeg",
        linkedin: "",
        xSocial: "",
        color: "linear-gradient(135deg, #8EB9FF, #D6C4FF)",
        text: "#000",
        description: "Exploration node contributing to creative growth through content and connection. Shaping the future network."
    }
];
